version: "3"
services:
    front:
        build: 
            context: ./
            dockerfile: Dockerfile.development   
            args:
                user: desenvolvedor # your username on your machine, you can get it by running echo $USER
                uid: 1000 
                group_id: 1000                      
        ports:
            - "8080:8080"
        volumes:
            - ./:/app
            #- '/app/node_modules'
        command: "npm run serve"
        tty: true
        container_name: "Estudo_vue"